"""empty message

Revision ID: d833159fb76e
Revises: 478e86622c2e
Create Date: 2016-10-12 11:37:54.040000

"""

# revision identifiers, used by Alembic.
revision = 'd833159fb76e'
down_revision = '478e86622c2e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column(u'table', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'table', 'location', ['location_id'], ['id'])
    op.drop_column(u'table', 'location')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'table', sa.Column('location', sa.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'table', type_='foreignkey')
    op.drop_column(u'table', 'location_id')
    op.drop_table('location')
    ### end Alembic commands ###
