"""empty message

Revision ID: e78e3897a9e6
Revises: a3e80913f720
Create Date: 2017-04-29 22:37:36.403712

"""

# revision identifiers, used by Alembic.
revision = 'e78e3897a9e6'
down_revision = 'a3e80913f720'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'note_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('note_type', sa.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###
